"""Tests for the checked-in reviewed backend inventory."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

from scripts.conformance.inventory import load_verified_inventory, review_summary

_PROJECT_ROOT = Path(__file__).parents[2]
_CANDIDATES_PATH = (
    _PROJECT_ROOT / "tests" / "truth" / "backend_inventory_candidates.json"
)
_INVENTORY_PATH = _PROJECT_ROOT / "tests" / "truth" / "backend_inventory.json"


# Q. Are all checked-in candidates represented by verified authoritative records?
def test_checked_in_candidates_are_fully_verified() -> None:
    candidates = json.loads(_CANDIDATES_PATH.read_text(encoding="utf-8"))
    candidate_records = candidates["records"]

    summary = review_summary(
        _CANDIDATES_PATH,
        _INVENTORY_PATH,
        root=_PROJECT_ROOT,
    )
    collected = load_verified_inventory(
        _CANDIDATES_PATH,
        _INVENTORY_PATH,
        root=_PROJECT_ROOT,
    )

    assert candidates["schema_version"] == 2
    assert len({record["id"] for record in candidate_records}) == len(candidate_records)
    assert summary["candidate_count"] == len(candidate_records)
    # Only independently validated records remain verified; the rest are excluded.
    assert summary["verified_count"] == 14
    assert summary["excluded_count"] == 589
    assert summary["unresolved_count"] == 0
    assert {record.id for record in collected} == {
        record["id"]
        for record in candidate_records
        if record["ground_truth_review"]["status"] == "verified"
    }


# Q. Can every reviewed fixture be checked out and discovered on every supported OS?
def test_checked_in_fixture_paths_are_portable_and_discoverable() -> None:
    candidates = json.loads(_CANDIDATES_PATH.read_text(encoding="utf-8"))["records"]
    fixture_paths = [record["fixture"] for record in candidates]
    path_counts = Counter(path.casefold() for path in fixture_paths)
    collisions = sorted(path for path, count in path_counts.items() if count > 1)
    discovered_paths = {
        path.relative_to(_PROJECT_ROOT).as_posix()
        for path in (_PROJECT_ROOT / "tests" / "fixtures").glob("sample.*")
    }

    assert collisions == []
    assert discovered_paths == set(fixture_paths)


# Q. Do reviewed conflict corrections retain only each fixture's probe extension?
def test_known_conflicts_corrected_and_7z_provenance_preserved() -> None:
    candidates = json.loads(_CANDIDATES_PATH.read_text(encoding="utf-8"))["records"]
    by_id = {record["id"]: record for record in candidates}

    assert by_id["sample-aiff"]["ground_truth"]["extensions"] == [".aiff"]
    assert by_id["sample-au"]["ground_truth"]["extensions"] == [".au"]
    assert by_id["sample-avif"]["ground_truth"]["extensions"] == [".avif"]
    # sample-aiff/sample-au: excluded pending independent format_validity validation
    assert by_id["sample-aiff"]["ground_truth_review"]["status"] == "excluded"
    assert by_id["sample-au"]["ground_truth_review"]["status"] == "excluded"
    # sample-7z: Tier-2 (pinned-SHA + py7zr round-trip), format_validity=verified
    assert by_id["sample-7z"]["ground_truth_review"]["status"] == "verified"
    assert (
        by_id["sample-7z"]["provenance"]
        == "Generated by py7zr in scripts/generators/archives.py:ArchiveGenerator._create_7z"
    )
