"""Tests for the checked-in legacy candidate inventory."""

from __future__ import annotations

import json
from pathlib import Path

from scripts.conformance.inventory import load_verified_inventory, review_summary


_PROJECT_ROOT = Path(__file__).parents[2]
_LEGACY_PATH = _PROJECT_ROOT / "tests" / "truth" / "canonical_fixtures.json"
_CANDIDATES_PATH = (
    _PROJECT_ROOT / "tests" / "truth" / "backend_inventory_candidates.json"
)
_INVENTORY_PATH = _PROJECT_ROOT / "tests" / "truth" / "backend_inventory.json"


# Q. Do checked-in candidates cover every legacy fixture and reflect current review progress?
def test_checked_in_candidates_cover_all_legacy_fixtures() -> None:
    legacy = json.loads(_LEGACY_PATH.read_text(encoding="utf-8"))
    candidates = json.loads(_CANDIDATES_PATH.read_text(encoding="utf-8"))

    summary = review_summary(
        _CANDIDATES_PATH,
        _INVENTORY_PATH,
        root=_PROJECT_ROOT,
    )
    collected = load_verified_inventory(
        _CANDIDATES_PATH,
        _INVENTORY_PATH,
        root=_PROJECT_ROOT,
    )

    assert candidates["schema_version"] == 1
    assert len(candidates["records"]) == len(legacy["fixtures"])
    assert {record["fixture"] for record in candidates["records"]} == {
        fixture["path"] for fixture in legacy["fixtures"]
    }
    assert len({record["id"] for record in candidates["records"]}) == len(
        candidates["records"]
    )
    # All candidates promoted to verified via batch review
    assert summary["candidate_count"] == len(legacy["fixtures"])
    assert summary["verified_count"] == len(legacy["fixtures"])
    assert summary["unresolved_count"] == 0
    assert len(collected) == len(legacy["fixtures"])


# Q. Do known legacy contradictions retain only the reviewed fixture extension?
def test_known_conflicts_corrected_and_7z_provenance_preserved() -> None:
    candidates = json.loads(_CANDIDATES_PATH.read_text(encoding="utf-8"))["records"]
    by_id = {record["id"]: record for record in candidates}

    assert by_id["sample-aiff"]["ground_truth"]["extensions"] == [".aiff"]
    assert by_id["sample-au"]["ground_truth"]["extensions"] == [".au"]
    assert by_id["sample-avif"]["ground_truth"]["extensions"] == [".avif"]
    assert by_id["sample-aiff"]["ground_truth_review"]["status"] == "verified"
    assert by_id["sample-avif"]["ground_truth_review"]["status"] == "verified"
    # Clean record promoted with corrected provenance
    assert by_id["sample-7z"]["ground_truth_review"]["status"] == "verified"
    assert (
        by_id["sample-7z"]["provenance"]
        == "Generated by py7zr in scripts/generators/archives.py:ArchiveGenerator._create_7z"
    )
