"""Tests for the checked-in legacy candidate inventory."""

from __future__ import annotations

import json
from pathlib import Path

from scripts.conformance.inventory import load_verified_inventory, review_summary


_PROJECT_ROOT = Path(__file__).parents[2]
_LEGACY_PATH = _PROJECT_ROOT / "tests" / "truth" / "canonical_fixtures.json"
_CANDIDATES_PATH = (
    _PROJECT_ROOT / "tests" / "truth" / "backend_inventory_candidates.json"
)
_INVENTORY_PATH = _PROJECT_ROOT / "tests" / "truth" / "backend_inventory.json"


# Q. Do checked-in candidates retain every legacy fixture claim without promoting it to Ground Truth?
def test_checked_in_candidates_cover_all_legacy_fixtures_pending_review() -> None:
    legacy = json.loads(_LEGACY_PATH.read_text(encoding="utf-8"))
    candidates = json.loads(_CANDIDATES_PATH.read_text(encoding="utf-8"))

    # Load and verify (review validation must keep all candidates out of collection)
    summary = review_summary(
        _CANDIDATES_PATH,
        _INVENTORY_PATH,
        root=_PROJECT_ROOT,
    )
    collected = load_verified_inventory(
        _CANDIDATES_PATH,
        _INVENTORY_PATH,
        root=_PROJECT_ROOT,
    )

    assert candidates["schema_version"] == 1
    assert len(candidates["records"]) == len(legacy["fixtures"])
    assert {record["fixture"] for record in candidates["records"]} == {
        fixture["path"] for fixture in legacy["fixtures"]
    }
    assert len({record["id"] for record in candidates["records"]}) == len(
        candidates["records"]
    )
    assert all(
        record["ground_truth_review"]["status"] == "needs_review"
        for record in candidates["records"]
    )
    assert summary["candidate_count"] == len(legacy["fixtures"])
    assert summary["verified_count"] == 0
    assert summary["unresolved_count"] == len(legacy["fixtures"])
    assert collected == ()


# Q. Do known legacy contradictions remain explicit candidates rather than silently normalized facts?
def test_known_conflicts_and_7z_provenance_remain_visible() -> None:
    candidates = json.loads(_CANDIDATES_PATH.read_text(encoding="utf-8"))["records"]
    by_id = {record["id"]: record for record in candidates}

    assert by_id["sample-aiff"]["ground_truth"]["extensions"] == [".txt"]
    assert by_id["sample-avif"]["ground_truth"]["extensions"] == [".mp4"]
    assert by_id["sample-aiff"]["ground_truth_review"]["status"] == "needs_review"
    assert by_id["sample-avif"]["ground_truth_review"]["status"] == "needs_review"
    assert (
        by_id["sample-7z"]["provenance"]
        == "Generated by py7zr in scripts/generators/archives.py:ArchiveGenerator._create_7z"
    )
