"""Auto-generated accuracy truth data for file type detection tests.

This module contains categorized fixture data used by test files to verify
that each inference strategy returns correct results. Categories:

- MAGIC_CORRECT: Magic returns a specific, correct MIME type. Hybrid should match.
- MAGIKA_IMPROVES: Magic is generic (text/plain, text/x-c, octet-stream),
  but Magika provides a specific MIME type. Hybrid must use Magika's result.
- MAGIC_WRONG: Magic returns a specific but incorrect MIME type.
  For text/* MIME types, Hybrid will use Magika if it provides better results.
- BOTH_GENERIC: Neither Magic nor Magika provides a specific MIME type.
- MAGIKA_FAILS: Magika returns empty result. Only Magic is available.

Each entry: (ext, magic_mime, magika_mime, magika_exts, magika_score, hybrid_mime, hybrid_ext)

Classification rules:
  - Magic "generic" = text/plain, text/x-c, or application/octet-stream
  - Magika "improves" = provides MIME type other than generic, with score >= 0.5
  - Hybrid MIME = the expected MIME from HybridInferencer for this file

DO NOT EDIT BY HAND. Regenerate with: python scripts/generate_truth_data.py
"""

# Magic returns the CORRECT specific MIME type.
# Hybrid should return the same result as Magic (no regression).
MAGIC_CORRECT = [
    ("7z", "application/x-7z-compressed", "application/x-7z-compressed", ['7z'], 0.947),
    ("aiff", "audio/x-aiff", "text/plain", ['txt'], 0.307),
    ("au", "audio/basic", "application/x-bplist", ['bplist', 'plist'], 0.776),
    ("avi", "video/x-msvideo", "application/octet-stream", [], 0.279),
    ("avif", "image/avif", "video/mp4", ['mp4'], 0.556),
    ("bmp", "image/bmp", "image/bmp", ['bmp'], 1.000),
    ("csv", "text/csv", "text/csv", ['csv'], 1.000),
    ("deb", "application/vnd.debian.binary-package", "application/octet-stream", [], 0.424),
    ("diff", "text/x-diff", "text/plain", ['diff', 'patch'], 1.000),
    ("doc", "application/msword", "application/msword", ['doc'], 1.000),
    ("docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", ['docx', 'docm'], 1.000),
    ("dwg", "image/vnd.dwg", "text/plain", ['txt'], 0.311),
    ("eml", "message/rfc822", "text/plain", ['txt'], 0.523),
    ("eot", "application/vnd.ms-fontobject", "application/octet-stream", [], 0.495),
    ("eps", "application/postscript", "application/postscript", ['ps'], 0.995),
    ("epub", "application/epub+zip", "application/epub+zip", ['epub'], 1.000),
    ("flac", "audio/flac", "image/bmp", ['bmp'], 0.527),
    ("flv", "video/x-flv", "video/x-flv", ['flv'], 0.680),
    ("gif", "image/gif", "image/gif", ['gif'], 1.000),
    ("h5", "application/x-hdf5", "application/x-hdf5", ['h5', 'hdf5'], 1.000),
    ("heic", "image/heic", "video/mp4", ['mp4'], 0.910),
    ("htm", "text/html", "text/html", ['html', 'htm', 'xhtml', 'xht'], 0.859),
    ("html", "text/html", "text/html", ['html', 'htm', 'xhtml', 'xht'], 0.859),
    ("hwp", "application/x-hwp", "image/vnd.ms-thumb", [], 0.830),
    ("ico", "image/vnd.microsoft.icon", "image/vnd.microsoft.icon", ['ico'], 0.976),
    ("ics", "text/calendar", "text/calendar", ['ics'], 1.000),
    ("iso", "application/x-iso9660-image", "application/x-iso9660-image", ['iso'], 0.999),
    ("java", "text/x-java", "text/x-java", ['java'], 0.562),
    ("jp2", "image/jp2", "image/jpeg2000", ['jp2'], 1.000),
    ("jpeg", "image/jpeg", "image/jpeg", ['jpg', 'jpeg'], 1.000),
    ("jpg", "image/jpeg", "image/jpeg", ['jpg', 'jpeg'], 1.000),
    ("json", "application/json", "application/json", ['json'], 0.994),
    ("jxl", "image/jxl", "application/octet-stream", [], 0.694),
    ("mht", "message/rfc822", "application/x-mimearchive", ['mht'], 0.987),
    ("midi", "audio/midi", "audio/midi", ['mid'], 1.000),
    ("mkv", "video/x-matroska", "video/x-matroska", ['mkv'], 0.747),
    ("mov", "video/quicktime", "video/quicktime", ['mov'], 0.973),
    ("mp3", "audio/mpeg", "audio/mpeg", ['mp3'], 1.000),
    ("mp4", "video/mp4", "video/mp4", ['mp4'], 0.996),
    ("odp", "application/vnd.oasis.opendocument.presentation", "application/vnd.oasis.opendocument.presentation", ['odp'], 0.967),
    ("ods", "application/vnd.oasis.opendocument.spreadsheet", "application/vnd.oasis.opendocument.spreadsheet", ['ods'], 0.997),
    ("odt", "application/vnd.oasis.opendocument.text", "application/vnd.oasis.opendocument.text", ['odt'], 0.999),
    ("patch", "text/x-diff", "text/plain", ['diff', 'patch'], 1.000),
    ("pcap", "application/vnd.tcpdump.pcap", "application/vnd.tcpdump.pcap", ['pcap', 'pcapng'], 1.000),
    ("pdf", "application/pdf", "application/pdf", ['pdf'], 0.996),
    ("pgp", "application/pgp-encrypted", "application/x-pem-file", ['pem', 'pub', 'gpg'], 0.991),
    ("pl", "text/x-perl", "text/x-perl", ['pl'], 1.000),
    ("png", "image/png", "image/png", ['png'], 1.000),
    ("ppt", "application/vnd.ms-powerpoint", "application/vnd.ms-powerpoint", ['ppt'], 1.000),
    ("pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation", "application/vnd.openxmlformats-officedocument.presentationml.presentation", ['pptx', 'pptm'], 1.000),
    ("ps", "application/postscript", "application/postscript", ['ps'], 0.976),
    ("psd", "image/vnd.adobe.photoshop", "application/octet-stream", [], 0.200),
    ("sqlite", "application/vnd.sqlite3", "application/octet-stream", ['sqlite', 'sqlite3'], 1.000),
    ("sqlite3", "application/vnd.sqlite3", "application/octet-stream", ['sqlite', 'sqlite3'], 1.000),
    ("svg", "image/svg+xml", "image/svg+xml", ['svg'], 0.994),
    ("tar", "application/x-tar", "application/x-tar", ['tar'], 1.000),
    ("tex", "text/x-tex", "text/x-tex", ['tex', 'sty'], 1.000),
    ("tif", "image/tiff", "image/bmp", ['bmp'], 0.569),
    ("tiff", "image/tiff", "image/bmp", ['bmp'], 0.569),
    ("torrent", "application/x-bittorrent", "application/x-bittorrent", ['torrent'], 1.000),
    ("vcard", "text/vcard", "text/calendar", ['ics'], 0.872),
    ("wav", "audio/x-wav", "audio/x-wav", ['wav'], 0.604),
    ("webm", "video/webm", "application/octet-stream", [], 0.436),
    ("webp", "image/webp", "image/webp", ['webp'], 0.832),
    ("xcf", "image/x-xcf", "text/plain", ['txt'], 0.616),
    ("xls", "application/vnd.ms-excel", "application/vnd.ms-excel", ['xls'], 1.000),
    ("xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ['xlsx', 'xlsm'], 1.000),
    ("zip", "application/zip", "application/zip", ['zip'], 0.951),
    ("zst", "application/zstd", "text/csv", ['csv'], 0.537),
]

# Magic returns a GENERIC MIME, but Magika provides a MORE SPECIFIC MIME.
# Hybrid MUST return Magika's result (this is the entire point of Hybrid).
MAGIKA_IMPROVES = [
    ("CBL", "text/plain", "text/x-cobol", ['cbl', 'cob', 'cpy', 'CBL', 'COB', 'CPY'], 0.999),
    ("COB", "text/plain", "text/x-cobol", ['cbl', 'cob', 'cpy', 'CBL', 'COB', 'CPY'], 0.999),
    ("F90", "text/plain", "text/x-fortran", ['f90', 'f95', 'f03', 'F90'], 0.959),
    ("P", "text/plain", "text/x-prolog", ['pl', 'pro', 'P'], 0.685),
    ("R", "text/plain", "text/x-R", ['R'], 0.992),
    ("aff", "text/plain", "text/x-msdos-batch", ['bat'], 0.601),
    ("asp", "text/plain", "text/html", ['aspx', 'asp'], 1.000),
    ("bib", "text/plain", "text/x-bibtex", ['bib'], 1.000),
    ("bluespec", "text/plain", "text/x-vhdl", ['vhd'], 0.637),
    ("bplist", "text/plain", "application/x-bplist", ['bplist', 'plist'], 0.931),
    ("cabal", "text/plain", "application/x-yaml", ['yml', 'yaml'], 0.968),
    ("cairo", "text/plain", "application/x-rust", ['rs'], 0.723),
    ("cbl", "text/plain", "text/x-cobol", ['cbl', 'cob', 'cpy', 'CBL', 'COB', 'CPY'], 0.999),
    ("cer", "application/octet-stream", "application/x-x509-ca-cert", ['der', 'cer', 'crt'], 1.000),
    ("chisel", "text/plain", "application/x-scala", ['scala'], 0.989),
    ("cjs", "text/x-c", "application/javascript", ['js', 'mjs', 'cjs'], 0.988),
    ("cmake", "text/plain", "text/x-cmake", ['cmake'], 0.972),
    ("cob", "text/plain", "text/x-cobol", ['cbl', 'cob', 'cpy', 'CBL', 'COB', 'CPY'], 0.999),
    ("coffee", "text/plain", "text/coffeescript", ['coffee'], 0.917),
    ("cpy", "text/plain", "text/x-cobol", ['cbl', 'cob', 'cpy', 'CBL', 'COB', 'CPY'], 0.999),
    ("crt", "text/plain", "application/x-pem-file", ['pem', 'pub', 'gpg'], 1.000),
    ("css", "text/plain", "text/css", ['css'], 0.581),
    ("cts", "text/plain", "application/typescript", ['ts', 'mts', 'cts'], 0.995),
    ("der", "application/octet-stream", "application/x-x509-ca-cert", ['der', 'cer', 'crt'], 1.000),
    ("dmg", "application/octet-stream", "application/x-apple-diskimage", ['dmg'], 0.987),
    ("erl", "text/plain", "text/x-erlang", ['erl', 'hrl'], 1.000),
    ("f03", "text/plain", "text/x-fortran", ['f90', 'f95', 'f03', 'F90'], 0.959),
    ("f90", "text/plain", "text/x-fortran", ['f90', 'f95', 'f03', 'F90'], 0.959),
    ("f95", "text/plain", "text/x-fortran", ['f90', 'f95', 'f03', 'F90'], 0.959),
    ("go", "text/x-c", "text/x-golang", ['go'], 0.982),
    ("gradle", "text/plain", "text/x-groovy", ['gradle'], 0.987),
    ("hcl", "text/plain", "text/x-hcl", ['hcl'], 0.996),
    ("hrl", "text/plain", "text/x-erlang", ['erl', 'hrl'], 0.997),
    ("js", "text/x-c", "application/javascript", ['js', 'mjs', 'cjs'], 0.988),
    ("litcoffee", "text/plain", "text/coffeescript", ['coffee'], 0.801),
    ("lnk", "application/octet-stream", "application/x-ms-shortcut", ['lnk'], 0.782),
    ("lock", "text/plain", "text/x-julia", ['jl'], 0.539),
    ("markdown", "text/plain", "text/markdown", ['md', 'markdown'], 0.996),
    ("matlab", "text/plain", "text/x-matlab", ['m', 'matlab'], 0.931),
    ("md", "text/plain", "text/markdown", ['md', 'markdown'], 0.996),
    ("mjs", "text/x-c", "application/javascript", ['js', 'mjs', 'cjs'], 0.988),
    ("ml", "text/plain", "text-ocaml", ['ml', 'mli'], 0.989),
    ("mli", "text/plain", "text-ocaml", ['ml', 'mli'], 0.922),
    ("mojo", "text/plain", "text/x-python", ['py', 'pyi'], 0.840),
    ("move", "text/plain", "application/x-rust", ['rs'], 0.967),
    ("mts", "text/plain", "application/typescript", ['ts', 'mts', 'cts'], 0.995),
    ("odin", "text/plain", "text/x-golang", ['go'], 0.663),
    ("p", "text/plain", "text/x-prolog", ['pl', 'pro', 'P'], 0.685),
    ("p6", "text/plain", "text/x-perl", ['pl'], 0.586),
    ("parquet", "application/octet-stream", "application/vnd.apache.parquet", ['pqt', 'parquet'], 1.000),
    ("pas", "text/plain", "text/x-pascal", ['pas', 'pp'], 1.000),
    ("pbtxt", "text/plain", "application/x-yaml", ['yml', 'yaml'], 0.828),
    ("pem", "text/plain", "application/x-pem-file", ['pem', 'pub', 'gpg'], 1.000),
    ("pl6", "text/plain", "text/x-perl", ['pl'], 0.586),
    ("pm6", "text/plain", "text/x-perl", ['pl'], 0.586),
    ("pp", "text/plain", "text/x-pascal", ['pas', 'pp'], 1.000),
    ("pro", "text/plain", "text/x-prolog", ['pl', 'pro', 'P'], 0.685),
    ("proto", "text/plain", "text/x-proto", ['proto'], 1.000),
    ("r", "text/plain", "text/x-R", ['R'], 0.998),
    ("raku", "text/plain", "text/x-perl", ['pl'], 0.586),
    ("raku6", "text/plain", "text/x-perl", ['pl'], 0.586),
    ("reg", "text/plain", "text/x-ms-regedit", ['reg'], 0.991),
    ("rs", "text/x-c", "application/x-rust", ['rs'], 0.527),
    ("rst", "text/plain", "text/x-rst", ['rst'], 0.952),
    ("rust", "text/x-c", "application/x-rust", ['rs'], 0.503),
    ("scala", "text/plain", "application/x-scala", ['scala'], 0.916),
    ("scm", "text/plain", "text/x-lisp", ['lisp', 'lsp', 'l', 'cl'], 0.999),
    ("scss", "text/plain", "text/x-scss", ['scss'], 0.963),
    ("snap", "text/plain", "application/sla", ['stl'], 0.934),
    ("sql", "text/plain", "application/x-sql", ['sql'], 0.999),
    ("srt", "text/plain", "text/srt", ['srt'], 1.000),
    ("ss", "text/plain", "text/x-lisp", ['lisp', 'lsp', 'l', 'cl'], 0.999),
    ("sty", "text/plain", "text/x-tex", ['tex', 'sty'], 0.996),
    ("swift", "text/x-c", "text/x-swift", ['swift'], 1.000),
    ("tcl", "text/plain", "application/x-tcl", ['tcl'], 0.988),
    ("textpb", "text/plain", "application/x-yaml", ['yml', 'yaml'], 0.828),
    ("textproto", "text/plain", "application/x-yaml", ['yml', 'yaml'], 0.828),
    ("tf", "text/plain", "text/x-hcl", ['hcl'], 1.000),
    ("toml", "text/plain", "application/toml", ['toml'], 0.996),
    ("tsv", "text/plain", "text/tsv", ['tsv'], 0.998),
    ("twig", "text/plain", "text/x-twig", ['twig'], 1.000),
    ("url", "text/plain", "application/x-mswinurl", ['url'], 1.000),
    ("v", "text/plain", "text/x-verilog", ['v', 'verilog', 'vlg', 'vh'], 0.995),
    ("vb", "text/plain", "text/vbscript", ['vbs', 'vba', 'vb'], 0.943),
    ("vba", "text/plain", "text/vbscript", ['vbs', 'vba', 'vb'], 0.989),
    ("vbe", "text/plain", "text/vbscript", ['vbs', 'vba', 'vb'], 0.943),
    ("vbs", "text/plain", "text/vbscript", ['vbs', 'vba', 'vb'], 0.866),
    ("verilog", "text/plain", "text/x-verilog", ['v', 'verilog', 'vlg', 'vh'], 0.995),
    ("vh", "text/plain", "text/x-verilog", ['v', 'verilog', 'vlg', 'vh'], 0.995),
    ("vhd", "text/plain", "text/x-vhdl", ['vhd'], 0.999),
    ("vlg", "text/plain", "text/x-verilog", ['v', 'verilog', 'vlg', 'vh'], 0.995),
    ("vtt", "text/plain", "text/vtt", ['vtt', 'webvtt'], 0.996),
    ("wad", "text/plain", "image/bmp", ['bmp'], 0.719),
    ("wasm", "application/octet-stream", "application/wasm", ['wasm'], 1.000),
    ("webvtt", "text/plain", "text/vtt", ['vtt', 'webvtt'], 0.996),
    ("woff2", "application/octet-stream", "font/woff2", ['woff2'], 1.000),
    ("yaml", "text/plain", "application/x-yaml", ['yml', 'yaml'], 0.731),
    ("yar", "text/plain", "text/x-yara", ['yar', 'yara'], 0.952),
    ("yara", "text/plain", "text/x-yara", ['yar', 'yara'], 0.952),
    ("yml", "text/plain", "application/x-yaml", ['yml', 'yaml'], 0.731),
    ("zig", "text/plain", "text/zig", ['zig'], 1.000),
]

# Magic returns a specific but INCORRECT MIME type.
# Known limitations of libmagic (e.g., .js -> text/x-c).
# For text/* MIME types, Hybrid uses Magika if it can improve.
MAGIC_WRONG = [
    ("3gp", "video/3gpp", "video/3gpp", ['3gp'], 0.988),
    ("S", "text/x-asm", "text/x-asm", ['s', 'S', 'asm'], 1.000),
    ("aac", "audio/x-hx-aac-adts", "application/octet-stream", [], 0.253),
    ("ai", "application/pdf", "application/pdf", ['pdf'], 0.996),
    ("apk", "application/zip", "application/zip", ['zip'], 0.963),
    ("arj", "application/x-arj", "application/octet-stream", [], 0.476),
    ("asc", "application/pgp-signature", "application/x-pem-file", ['pem', 'pub', 'gpg'], 0.996),
    ("asf", "video/x-ms-asf", "application/octet-stream", [], 0.726),
    ("asm", "text/x-asm", "text/x-asm", ['s', 'S', 'asm'], 1.000),
    ("aspx", "text/html", "text/html", ['aspx', 'asp'], 0.998),
    ("aux", "text/x-tex", "text/x-tex", ['tex', 'sty'], 0.999),
    ("avifs", "image/avif", "video/mp4", ['mp4'], 0.556),
    ("ax", "application/x-dosexec", "application/x-dosexec", ['exe', 'dll'], 0.733),
    ("bat", "text/x-msdos-batch", "text/x-msdos-batch", ['bat'], 1.000),
    ("bz2", "application/x-bzip2", "application/x-bzip2", ['bz2', 'tbz2', 'tar.bz2'], 1.000),
    ("bzl", "text/x-script.python", "text/plain", ['bzl'], 0.960),
    ("cjsx", "text/x-java", "application/javascript", ['js', 'mjs', 'cjs'], 0.603),
    ("cl", "text/x-lisp", "text/x-lisp", ['lisp', 'lsp', 'l', 'cl'], 0.991),
    ("class", "application/x-java-applet", "application/octet-stream", [], 0.264),
    ("clj", "text/x-clojure", "text/x-clojure", ['clj', 'cljs', 'cljc', 'cljr'], 1.000),
    ("cljr", "text/x-clojure", "text/x-clojure", ['clj', 'cljs', 'cljc', 'cljr'], 0.999),
    ("cljs", "text/x-clojure", "text/x-clojure", ['clj', 'cljs', 'cljc', 'cljr'], 0.999),
    ("cpl", "application/x-dosexec", "application/x-dosexec", ['exe', 'dll'], 0.733),
    ("crx", "application/x-chrome-extension", "application/octet-stream", [], 0.486),
    ("cs", "text/x-c++", "text/plain", ['cs', 'csx'], 0.981),
    ("csx", "text/x-c++", "text/plain", ['cs', 'csx'], 0.981),
    ("ctsx", "text/x-java", "application/typescript", ['ts', 'mts', 'cts'], 1.000),
    ("db", "application/vnd.sqlite3", "application/octet-stream", ['sqlite', 'sqlite3'], 1.000),
    ("dll", "application/x-dosexec", "application/x-dosexec", ['exe', 'dll'], 1.000),
    ("docm", "application/zip", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", ['docx', 'docm'], 0.980),
    ("dotx", "application/zip", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", ['docx', 'docm'], 0.980),
    ("dxf", "application/x-dxf", "image/vnd.dxf", ['dxf'], 1.000),
    ("dylib", "application/x-mach-binary", "application/octet-stream", [], 0.291),
    ("elf", "application/x-executable", "application/octet-stream", [], 0.231),
    ("erb", "text/html", "text/x-ruby", ['erb'], 0.990),
    ("ex", "text/x-ruby", "text/plain", ['exs'], 0.996),
    ("exe", "application/x-dosexec", "application/x-dosexec", ['exe', 'dll'], 1.000),
    ("exs", "text/x-ruby", "text/plain", ['exs'], 0.996),
    ("gpg", "application/pgp-keys", "application/x-pem-file", ['pem', 'pub', 'gpg'], 0.998),
    ("gpx", "text/xml", "text/xml", ['xml'], 0.749),
    ("groovy", "text/x-c++", "text/x-groovy", ['groovy'], 0.976),
    ("gz", "application/gzip", "application/gzip", ['gz', 'gzip', 'tgz', 'tar.gz'], 1.000),
    ("gzip", "application/gzip", "application/gzip", ['gz', 'gzip', 'tgz', 'tar.gz'], 1.000),
    ("handlebars", "text/html", "text/x-handlebars-template", ['hbs', 'handlebars'], 0.997),
    ("hbs", "text/html", "text/x-handlebars-template", ['hbs', 'handlebars'], 0.997),
    ("hdf5", "application/x-hdf5", "application/x-hdf5", ['h5', 'hdf5'], 1.000),
    ("heics", "image/heic", "video/mp4", ['mp4'], 0.910),
    ("heif", "image/heic", "video/mp4", ['mp4'], 0.910),
    ("heifs", "image/heic", "video/mp4", ['mp4'], 0.910),
    ("hta", "text/html", "text/html", ['aspx', 'asp'], 0.987),
    ("hwpx", "application/zip", "application/epub+zip", ['epub'], 0.548),
    ("icns", "image/x-icns", "application/octet-stream", [], 0.241),
    ("ipynb", "application/json", "application/json", ['ipynb'], 1.000),
    ("j2", "text/html", "text/x-twig", ['twig'], 0.682),
    ("jar", "application/zip", "application/zip", ['zip'], 0.951),
    ("jinja", "text/html", "text/x-twig", ['twig'], 0.682),
    ("jinja2", "text/html", "text/x-twig", ['twig'], 0.682),
    ("jnlp", "text/xml", "text/xml", ['xml'], 0.983),
    ("jsonl", "application/json", "application/json", ['jsonl', 'jsonld'], 0.999),
    ("jsonld", "application/json", "application/json", ['jsonl', 'jsonld'], 0.998),
    ("jsx", "text/x-java", "application/javascript", ['js', 'mjs', 'cjs'], 0.603),
    ("ko", "application/x-executable", "application/octet-stream", [], 0.231),
    ("ksh", "text/x-shellscript", "text/x-shellscript", ['sh'], 0.995),
    ("l", "text/x-lisp", "text/x-lisp", ['lisp', 'lsp', 'l', 'cl'], 0.991),
    ("lisp", "text/x-lisp", "text/x-lisp", ['lisp', 'lsp', 'l', 'cl'], 0.991),
    ("lsp", "text/x-lisp", "text/x-lisp", ['lisp', 'lsp', 'l', 'cl'], 0.991),
    ("lz", "application/x-lzma", "application/octet-stream", [], 0.460),
    ("lz4", "application/x-lz4", "application/octet-stream", [], 0.374),
    ("m", "text/x-objective-c", "text/x-objcsrc", ['m', 'mm'], 0.982),
    ("m4", "text/x-m4", "text/plain", ['m4'], 1.000),
    ("maff", "application/zip", "application/zip", ['zip'], 0.990),
    ("makefile", "text/x-makefile", "text/x-makefile", [], 1.000),
    ("mid", "audio/midi", "audio/midi", ['mid'], 1.000),
    ("mjsx", "text/x-java", "application/javascript", ['js', 'mjs', 'cjs'], 0.603),
    ("mm", "text/x-objective-c", "text/x-objcsrc", ['m', 'mm'], 0.982),
    ("msi", "application/CDFV2", "application/octet-stream", [], 0.247),
    ("mtsx", "text/x-java", "application/typescript", ['ts', 'mts', 'cts'], 1.000),
    ("npz", "application/zip", "application/octet-stream", ['npz'], 1.000),
    ("nupkg", "application/zip", "application/zip", ['zip'], 0.939),
    ("o", "application/x-coff", "application/x-coff", ['obj', 'o'], 0.992),
    ("obj", "application/x-coff", "application/x-coff", ['obj', 'o'], 0.992),
    ("ocx", "application/x-dosexec", "application/x-dosexec", ['exe', 'dll'], 0.733),
    ("one", "application/CDFV2", "application/octet-stream", [], 0.247),
    ("otf", "application/vnd.ms-opentype", "font/otf", ['otf'], 0.734),
    ("php", "text/x-php", "text/x-php", ['php'], 0.999),
    ("pkg", "application/x-xar", "application/octet-stream", [], 0.167),
    ("plist", "text/xml", "application/x-plist", ['plist'], 0.997),
    ("po", "text/x-po", "text/gettext-translation", ['po'], 1.000),
    ("pot", "text/x-po", "text/gettext-translation", ['po'], 1.000),
    ("pptm", "application/zip", "application/vnd.openxmlformats-officedocument.presentationml.presentation", ['pptx', 'pptm'], 0.993),
    ("py", "text/x-script.python", "text/x-python", ['py', 'pyi'], 1.000),
    ("rar", "application/x-rar", "application/x-rar", ['rar'], 0.955),
    ("rb", "text/x-ruby", "application/x-ruby", ['rb'], 0.999),
    ("rdf", "text/xml", "application/rdf+xml", ['rdf'], 0.999),
    ("rlib", "application/x-archive", "application/octet-stream", [], 0.221),
    ("rll", "application/x-dosexec", "application/x-dosexec", ['exe', 'dll'], 0.733),
    ("rpm", "application/x-rpm", "application/sla", ['stl'], 0.630),
    ("rtf", "text/rtf", "text/rtf", ['rtf'], 0.998),
    ("rz", "application/gzip", "application/gzip", ['gz', 'gzip', 'tgz', 'tar.gz'], 1.000),
    ("s", "text/x-asm", "text/x-asm", ['s', 'S', 'asm'], 1.000),
    ("scr", "application/x-dosexec", "application/x-dosexec", ['exe', 'dll'], 0.733),
    ("sh", "text/x-shellscript", "text/x-shellscript", ['sh'], 0.997),
    ("smali", "text/x-java", "application/x-smali", ['smali'], 1.000),
    ("so", "application/x-executable", "application/octet-stream", [], 0.231),
    ("sys", "application/x-dosexec", "application/x-dosexec", ['exe', 'dll'], 0.733),
    ("bz2", "application/x-bzip2", "application/x-bzip2", ['bz2', 'tbz2', 'tar.bz2'], 1.000),
    ("gz", "application/gzip", "application/gzip", ['gz', 'gzip', 'tgz', 'tar.gz'], 1.000),
    ("tbz2", "application/x-bzip2", "application/x-bzip2", ['bz2', 'tbz2', 'tar.bz2'], 1.000),
    ("tga", "image/x-tga", "image/bmp", ['bmp'], 0.510),
    ("tgz", "application/gzip", "application/gzip", ['gz', 'gzip', 'tgz', 'tar.gz'], 1.000),
    ("tsx", "text/x-java", "application/typescript", ['ts', 'mts', 'cts'], 1.000),
    ("ttc", "font/ttf", "application/octet-stream", [], 0.304),
    ("ttf", "font/sfnt", "application/x-coff", ['obj', 'o'], 0.931),
    ("vcxproj", "text/xml", "application/xml", ['vcxproj'], 0.596),
    ("vdw", "application/zip", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", ['docx', 'docm'], 0.604),
    ("vsd", "application/CDFV2", "application/octet-stream", [], 0.247),
    ("vsdm", "application/zip", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", ['docx', 'docm'], 0.604),
    ("vsdx", "application/zip", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", ['docx', 'docm'], 0.604),
    ("vue", "text/html", "application/javascript", ['vue'], 0.999),
    ("wma", "video/x-ms-asf", "application/octet-stream", [], 0.726),
    ("wmv", "video/x-ms-asf", "application/octet-stream", [], 0.726),
    ("xar", "application/x-xar", "application/octet-stream", [], 0.167),
    ("xht", "text/html", "text/html", ['html', 'htm', 'xhtml', 'xht'], 0.859),
    ("xhtml", "text/html", "text/html", ['html', 'htm', 'xhtml', 'xht'], 0.859),
    ("xlsb", "application/zip", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ['xlsb'], 0.949),
    ("xlsm", "application/zip", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ['xlsx', 'xlsm'], 0.997),
    ("xml", "text/xml", "text/xml", ['xml'], 0.995),
    ("xpi", "application/zip", "application/zip", ['zip'], 0.951),
    ("xsd", "text/xml", "text/xml", ['xml'], 0.996),
    ("xz", "application/x-xz", "application/x-xz", ['xz'], 1.000),
    ("z", "application/x-compress", "application/octet-stream", [], 0.339),
]

# Neither Magic nor Magika provides a specific MIME type.
# Both return generic results. Hybrid cannot improve over Magic here.
BOTH_GENERIC = [
    ("CPY", "text/plain", "text/plain", ['txt'], 0.372),
    ("a68", "text/plain", "text/plain", ['awk'], 0.970),
    ("abnf", "text/plain", "text/plain", ['txt'], 0.215),
    ("agda", "text/plain", "text/plain", ['hs', 'lhs'], 0.974),
    ("aidl", "text/plain", "text/plain", ['txt'], 0.490),
    ("au3", "text/plain", "text/plain", ['au3'], 0.990),
    ("avro", "application/octet-stream", "text/plain", ['txt'], 0.498),
    ("awk", "text/plain", "text/plain", ['awk'], 1.000),
    ("b", "text/plain", "text/plain", ['txt'], 0.376),
    ("bdf", "text/plain", "text/plain", ['txt'], 0.478),
    ("bf", "text/plain", "text/plain", ['txt'], 0.376),
    ("bfm", "text/plain", "text/plain", ['txt'], 0.509),
    ("brf", "text/plain", "text/plain", ['txt'], 0.509),
    ("c", "text/x-c", "text/x-c", ['c'], 0.995),
    ("c++", "text/x-c", "text/x-c", ['cc', 'cpp', 'cxx', 'c++', 'cppm', 'ixx'], 0.933),
    ("cab", "application/octet-stream", "text/plain", ['txt'], 0.343),
    ("carbon", "text/plain", "text/plain", ['txt'], 0.391),
    ("cc", "text/x-c", "text/x-c", ['cc', 'cpp', 'cxx', 'c++', 'cppm', 'ixx'], 0.933),
    ("cpp", "text/x-c", "text/x-c", ['cc', 'cpp', 'cxx', 'c++', 'cppm', 'ixx'], 0.933),
    ("cppm", "text/x-c", "text/x-c", ['cc', 'cpp', 'cxx', 'c++', 'cppm', 'ixx'], 0.933),
    ("csproj", "text/plain", "text/plain", ['csproj'], 0.999),
    ("cxx", "text/x-c", "text/x-c", ['cc', 'cpp', 'cxx', 'c++', 'cppm', 'ixx'], 0.933),
    ("dart", "text/x-c", "text/plain", ['dart'], 0.978),
    ("dhall", "text/plain", "text/plain", ['txt'], 0.167),
    ("dm", "text/plain", "text/plain", ['txt'], 0.247),
    ("dmigd", "text/plain", "text/plain", ['txt'], 0.247),
    ("elm", "text/plain", "text/plain", ['hs', 'lhs'], 1.000),
    ("firrtl", "text/plain", "text/plain", ['txt'], 0.249),
    ("gemspec", "text/plain", "text/plain", ['gemspec'], 0.974),
    ("gleam", "text/x-c", "text/plain", ['kt', 'kts'], 0.595),
    ("glsl", "text/x-c", "text/plain", ['txt'], 0.333),
    ("h", "text/x-c", "text/x-c", ['c'], 0.991),
    ("h++", "text/x-c", "text/x-c", ['cc', 'cpp', 'cxx', 'c++', 'cppm', 'ixx'], 0.793),
    ("hh", "text/x-c", "text/x-c", ['cc', 'cpp', 'cxx', 'c++', 'cppm', 'ixx'], 0.793),
    ("hlsl", "text/plain", "text/plain", ['sol'], 0.822),
    ("hpp", "text/x-c", "text/x-c", ['cc', 'cpp', 'cxx', 'c++', 'cppm', 'ixx'], 0.793),
    ("hs", "text/plain", "text/plain", ['hs', 'lhs'], 0.998),
    ("hxx", "text/x-c", "text/x-c", ['cc', 'cpp', 'cxx', 'c++', 'cppm', 'ixx'], 0.793),
    ("idr", "text/plain", "text/plain", ['hs', 'lhs'], 0.999),
    ("ini", "text/plain", "text/plain", ['ini'], 0.974),
    ("ixx", "text/x-c", "text/x-c", ['cc', 'cpp', 'cxx', 'c++', 'cppm', 'ixx'], 0.933),
    ("jl", "text/plain", "text/plain", ['lua'], 0.687),
    ("kt", "text/x-c", "text/plain", ['kt', 'kts'], 0.999),
    ("kts", "text/x-c", "text/plain", ['kt', 'kts'], 0.999),
    ("lean", "text/plain", "text/plain", ['txt'], 0.463),
    ("lhs", "text/plain", "text/plain", ['hs', 'lhs'], 0.777),
    ("lua", "text/plain", "text/plain", ['lua'], 0.932),
    ("m2t", "application/octet-stream", "text/plain", ['txt'], 0.215),
    ("m3u", "text/plain", "text/plain", ['m3u8', 'm3u'], 0.995),
    ("m3u8", "text/plain", "text/plain", ['m3u8', 'm3u'], 0.995),
    ("metal", "text/x-c", "text/x-c", ['cc', 'cpp', 'cxx', 'c++', 'cppm', 'ixx'], 0.795),
    ("mlir", "text/x-c", "text/plain", ['txt'], 0.366),
    ("nix", "text/plain", "text/plain", ['txt'], 0.232),
    ("npy", "application/octet-stream", "application/octet-stream", ['npy'], 0.943),
    ("onnx", "application/octet-stream", "application/octet-stream", ['onnx'], 1.000),
    ("pb", "application/octet-stream", "text/plain", ['txt'], 0.700),
    ("pickle", "application/octet-stream", "application/octet-stream", ['pickle', 'pkl'], 1.000),
    ("pkl", "application/octet-stream", "application/octet-stream", ['pickle', 'pkl'], 1.000),
    ("protobuf", "application/octet-stream", "text/plain", ['txt'], 0.700),
    ("ps1", "text/plain", "text/plain", ['txt'], 0.348),
    ("pt", "application/octet-stream", "application/octet-stream", ['pickle', 'pkl'], 0.996),
    ("pth", "application/octet-stream", "application/octet-stream", ['pickle', 'pkl'], 0.996),
    ("pub", "text/plain", "text/plain", ['txt'], 0.259),
    ("purs", "text/plain", "text/plain", ['hs', 'lhs'], 1.000),
    ("pyi", "text/plain", "text/plain", ['txt'], 0.227),
    ("roc", "text/plain", "text/plain", ['txt'], 0.446),
    ("sgml", "text/plain", "text/plain", ['txt'], 0.299),
    ("sol", "text/plain", "text/plain", ['sol'], 1.000),
    ("spv", "text/plain", "text/plain", ['txt'], 0.357),
    ("sum", "text/plain", "text/plain", ['txt'], 0.523),
    ("text", "text/plain", "text/plain", ['txt'], 0.321),
    ("ts", "application/octet-stream", "text/plain", ['txt'], 0.215),
    ("txt", "text/plain", "text/plain", ['txt'], 0.321),
    ("vim", "text/plain", "text/plain", ['txt'], 0.365),
    ("wgsl", "text/x-c", "text/plain", ['txt'], 0.410),
]

# Magika returns an empty result. Only Magic is available.
MAGIKA_FAILS = [
    ("arc", "application/octet-stream", "application/octet-stream", [], 0.305),
    ("chm", "application/octet-stream", "application/octet-stream", [], 0.400),
    ("dcm", "application/octet-stream", "application/octet-stream", [], 0.164),
    ("dex", "application/octet-stream", "application/octet-stream", [], 0.217),
    ("dockerfile", "text/plain", "text/x-dockerfile", [], 1.000),
    ("jng", "application/octet-stream", "application/octet-stream", [], 0.216),
    ("lha", "text/plain", "application/octet-stream", [], 0.198),
    ("lrz", "text/plain", "application/octet-stream", [], 0.446),
    ("lzh", "text/plain", "application/octet-stream", [], 0.198),
    ("odex", "application/octet-stream", "application/octet-stream", [], 0.217),
    ("oga", "application/octet-stream", "application/octet-stream", [], 0.438),
    ("ogg", "application/octet-stream", "application/octet-stream", [], 0.438),
    ("opus", "application/octet-stream", "application/octet-stream", [], 0.438),
    ("pcapng", "application/octet-stream", "application/octet-stream", [], 0.145),
    ("pyc", "text/plain", "application/octet-stream", [], 0.323),
    ("pyo", "text/plain", "application/octet-stream", [], 0.323),
    ("qoi", "application/octet-stream", "application/octet-stream", [], 0.359),
    ("stl", "application/octet-stream", "application/octet-stream", [], 0.301),
    ("swf", "application/octet-stream", "application/octet-stream", [], 0.225),
    ("woff", "application/octet-stream", "application/octet-stream", [], 0.471),
]
