"""Generate sample.ahk fixture and add to candidates."""

import hashlib
import json
import os
import sys

ROOT = "/mnt/workspace/projects/file_type_detector-backend-conformance"
sys.path.insert(0, ROOT)

from scripts.generators.code_formats import CodeFormatGenerator  # noqa: E402

g = CodeFormatGenerator()
data = g.generate("ahk")
sha256 = hashlib.sha256(data).hexdigest()

fixture_path = os.path.join(ROOT, "tests/fixtures/sample.ahk")
with open(fixture_path, "wb") as f:
    f.write(data)
print(f"fixture: {len(data)}B sha={sha256}")

# Add to candidates
cand_path = os.path.join(ROOT, "tests/truth/backend_inventory_candidates.json")
cand = json.load(open(cand_path))

new_record = {
    "id": "sample-ahk",
    "fixture": "tests/fixtures/sample.ahk",
    "sha256": sha256,
    "probe_extension": ".ahk",
    "ground_truth": {
        "mime_types": ["text/plain"],
        "extensions": [".ahk"],
    },
    "provenance": "Generated by CodeFormatGenerator._ahk (AutoHotkey script)",
    "ground_truth_review": {
        "status": "needs_review",
        "reason": "New fixture; independent format validity review required",
    },
    "backends": ["lexical", "magic", "magika", "hybrid"],
}

if not any(r["id"] == "sample-ahk" for r in cand["records"]):
    cand["records"].append(new_record)
    json.dump(cand, open(cand_path, "w"), indent=1)
    print(f"added to candidates: {len(cand['records'])} total")
else:
    print("already in candidates")
